using System;

namespace FluGASv25.Models.Properties
{
    public class Reference
    {
        public Int32 ID { get; set; }
        public string DATE { get; set; }
        // Type A
        public Int32 AHAminLength { get; set; }
        public Int32 AMPminLength { get; set; }
        public Int32 ANAminLength { get; set; }
        public Int32 ANPminLength { get; set; }
        public Int32 ANSminLength { get; set; }
        public Int32 APAminLength { get; set; }
        public Int32 APB1minLength { get; set; }
        public Int32 APB2minLength { get; set; }
        public Int32 AHAmaxLength { get; set; }
        public Int32 AMPmaxLength { get; set; }
        public Int32 ANAmaxLength { get; set; }
        public Int32 ANPmaxLength { get; set; }
        public Int32 ANSmaxLength { get; set; }
        public Int32 APAmaxLength { get; set; }
        public Int32 APB1maxLength { get; set; }
        public Int32 APB2maxLength { get; set; }
        public string AHA5nuc { get; set; }
        public string AMP5nuc { get; set; }
        public string ANA5nuc { get; set; }
        public string ANP5nuc { get; set; }
        public string ANS5nuc { get; set; }
        public string APA5nuc { get; set; }
        public string APB15nuc { get; set; }
        public string APB25nuc { get; set; }
        public string AHA3nuc { get; set; }
        public string AMP3nuc { get; set; }
        public string ANA3nuc { get; set; }
        public string ANP3nuc { get; set; }
        public string ANS3nuc { get; set; }
        public string APA3nuc { get; set; }
        public string APB13nuc { get; set; }
        public string APB23nuc { get; set; }
        public Int32 AHAincN { get; set; }
        public Int32 AMPincN { get; set; }
        public Int32 ANAincN { get; set; }
        public Int32 ANPincN { get; set; }
        public Int32 ANSincN { get; set; }
        public Int32 APAincN { get; set; }
        public Int32 APB1incN { get; set; }
        public Int32 APB2incN { get; set; }
        public string AHAmapcdhit { get; set; }
        public string AMPmapcdhit { get; set; }
        public string ANAmapcdhit { get; set; }
        public string ANPmapcdhit { get; set; }
        public string ANSmapcdhit { get; set; }
        public string APAmapcdhit { get; set; }
        public string APB1mapcdhit { get; set; }
        public string APB2mapcdhit { get; set; }
        public string AHAbltcdhit { get; set; }
        public string AMPbltcdhit { get; set; }
        public string ANAbltcdhit { get; set; }
        public string ANPbltcdhit { get; set; }
        public string ANSbltcdhit { get; set; }
        public string APAbltcdhit { get; set; }
        public string APB1bltcdhit { get; set; }
        public string APB2bltcdhit { get; set; }
        public Int32 AHAminCDS { get; set; }
        public Int32 AMPminCDS { get; set; }
        public Int32 ANAminCDS { get; set; }
        public Int32 ANPminCDS { get; set; }
        public Int32 ANSminCDS { get; set; }
        public Int32 APAminCDS { get; set; }
        public Int32 APB1minCDS { get; set; }
        public Int32 APB2minCDS { get; set; }
        public Int32 AHAmaxCDS { get; set; }
        public Int32 AMPmaxCDS { get; set; }
        public Int32 ANAmaxCDS { get; set; }
        public Int32 ANPmaxCDS { get; set; }
        public Int32 ANSmaxCDS { get; set; }
        public Int32 APAmaxCDS { get; set; }
        public Int32 APB1maxCDS { get; set; }
        public Int32 APB2maxCDS { get; set; }


        public Int32 BHAminLength { get; set; }
        public Int32 BMPminLength { get; set; }
        public Int32 BNAminLength { get; set; }
        public Int32 BNPminLength { get; set; }
        public Int32 BNSminLength { get; set; }
        public Int32 BPAminLength { get; set; }
        public Int32 BPB1minLength { get; set; }
        public Int32 BPB2minLength { get; set; }
        public Int32 BHAmaxLength { get; set; }
        public Int32 BMPmaxLength { get; set; }
        public Int32 BNAmaxLength { get; set; }
        public Int32 BNPmaxLength { get; set; }
        public Int32 BNSmaxLength { get; set; }
        public Int32 BPAmaxLength { get; set; }
        public Int32 BPB1maxLength { get; set; }
        public Int32 BPB2maxLength { get; set; }
        public string BHA5nuc { get; set; }
        public string BMP5nuc { get; set; }
        public string BNA5nuc { get; set; }
        public string BNP5nuc { get; set; }
        public string BNS5nuc { get; set; }
        public string BPA5nuc { get; set; }
        public string BPB15nuc { get; set; }
        public string BPB25nuc { get; set; }
        public string BHA3nuc { get; set; }
        public string BMP3nuc { get; set; }
        public string BNA3nuc { get; set; }
        public string BNP3nuc { get; set; }
        public string BNS3nuc { get; set; }
        public string BPA3nuc { get; set; }
        public string BPB13nuc { get; set; }
        public string BPB23nuc { get; set; }
        public Int32 BHAincN { get; set; }
        public Int32 BMPincN { get; set; }
        public Int32 BNAincN { get; set; }
        public Int32 BNPincN { get; set; }
        public Int32 BNSincN { get; set; }
        public Int32 BPAincN { get; set; }
        public Int32 BPB1incN { get; set; }
        public Int32 BPB2incN { get; set; }
        public string BHAmapcdhit { get; set; }
        public string BMPmapcdhit { get; set; }
        public string BNAmapcdhit { get; set; }
        public string BNPmapcdhit { get; set; }
        public string BNSmapcdhit { get; set; }
        public string BPAmapcdhit { get; set; }
        public string BPB1mapcdhit { get; set; }
        public string BPB2mapcdhit { get; set; }
        public string BHAbltcdhit { get; set; }
        public string BMPbltcdhit { get; set; }
        public string BNAbltcdhit { get; set; }
        public string BNPbltcdhit { get; set; }
        public string BNSbltcdhit { get; set; }
        public string BPAbltcdhit { get; set; }
        public string BPB1bltcdhit { get; set; }
        public string BPB2bltcdhit { get; set; }
        public Int32 BHAminCDS { get; set; }
        public Int32 BMPminCDS { get; set; }
        public Int32 BNAminCDS { get; set; }
        public Int32 BNPminCDS { get; set; }
        public Int32 BNSminCDS { get; set; }
        public Int32 BPAminCDS { get; set; }
        public Int32 BPB1minCDS { get; set; }
        public Int32 BPB2minCDS { get; set; }
        public Int32 BHAmaxCDS { get; set; }
        public Int32 BMPmaxCDS { get; set; }
        public Int32 BNAmaxCDS { get; set; }
        public Int32 BNPmaxCDS { get; set; }
        public Int32 BNSmaxCDS { get; set; }
        public Int32 BPAmaxCDS { get; set; }
        public Int32 BPB1maxCDS { get; set; }
        public Int32 BPB2maxCDS { get; set; }
    }
}
